base:
  project: Compressive-strength
  random_state: 37
  target_col: Concrete compressive strength


data_source:
  raw_data: data/raw/Concrete_Data.csv

load_data:
  raw_data: data/raw/Concrete_raw.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      max_depth: 4
      n_estimators: 200
      

model_dir: saved_models

report:
  scores: report/scores.json
  params: report/params.json